### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by MorganaLF** [Nelliza/hotel#11]
Чтобы избежать дублирования, здесь можно использовать интерполяцию в тэге, и сразу же установить дефолтное значение: 

`#{tag || "button"}`

![Снимок экрана в 2019-08-05 11-34-50](https://user-images.githubusercontent.com/38564412/62450665-6bd9c000-b775-11e9-944c-40ed42926090.png)

**Comment by Nelliza** [comment]
Вариант с интерполяцией в теге симпатичный, раньше меня смущало, как задавать в этом случае специфичные для каждого тега атрибуты (type для button, href для a), но решение нашлось. Единственный момент - дефолтное значение для tag было задано при объявлении миксина (tag="a"), поэтому первый операнд вот здесь #{tag || "button"} всегда будет true, предлагаю убрать логический оператор в интерполяции и оставить #{tag}

**Comment by MorganaLF** [comment]
Да, не заметила дефолтный тег)

Еще сразу здесь напишу, но это касается и pug, и js во всех проектах: нужно использовать строгое сравнение ===, вместо ==. Поскольку == производит приведение типов и можно получить некорректные результаты.

**Comment by Nelliza** [comment]
> Да, не заметила дефолтный тег)
> 
> Еще сразу здесь напишу, но это касается и pug, и js во всех проектах: нужно использовать строгое сравнение ===, вместо ==. Поскольку == производит приведение типов и можно получить некорректные результаты.

В js стараюсь придерживаться этого правила, а вот pug почему-то недооценен мной )
