### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by MorganaLF** [Nelliza/hotel#14]
> Конструктор класса должен быть максимально легковесным;
> 
> Например, если требуется провести поиск по DOM-дереву для задания значений полям класса, то нужно вынести этот функционал в отдельный метод.

Нужно убрать поиск по DOM из конструкторов классов.

![Снимок экрана в 2019-08-05 13-20-36](https://user-images.githubusercontent.com/38564412/62457620-e4e01400-b783-11e9-9de7-bee4a161b93a.png)

**Comment by MorganaLF** [comment]
**Button.js**

https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/naming.md

> Имя переменной должно полно и точно описывать сущность и ее предназначение

Лучше не использовать сокращения в именах переменных: btn, pos и т.д. Имя div тоже малоинформативно, это ведь не просто div, а div для ripple?

![Снимок экрана в 2019-08-05 13-15-44](https://user-images.githubusercontent.com/38564412/62457863-54560380-b784-11e9-8eb5-153490f1631c.png)

**Comment by MorganaLF** [comment]
Вот здесь тоже не очень подходящие имена всех трех переменных, в переменной email лежит не просто мейл, а поле, тут лучше подойдет emailField, а valEmail это скорее всего как раз email будет

![Снимок экрана в 2019-08-05 13-29-23](https://user-images.githubusercontent.com/38564412/62458326-481e7600-b785-11e9-840c-95fdf4c716b8.png)

**Comment by MorganaLF** [comment]
В **Location.js** все лежит в одном методе, причем метод init не только инициализирует. Думаю, здесь было бы лучше создать отдельный метод для создания маркера.

**Comment by MorganaLF** [comment]
Почему здесь для инициализации используется один класс, а в плагин передается другой?

![Снимок экрана в 2019-08-05 13-37-03](https://user-images.githubusercontent.com/38564412/62458683-36899e00-b786-11e9-832e-096740aaa31f.png)

**Comment by Nelliza** [comment]
> Почему здесь для инициализации используется один класс, а в плагин передается другой?

Потому что этот плагин общий для реализации анимации как pie-chart, так и percentage, и ему нужно имя класса для добавления модификатора соответствующему DOM-элементу. Я так поняла, класс (модификатор), добавляющийся в целях изменения стилей у элемента, не должен начинаться с префикса -js, но могу ошибаться )

**Comment by MorganaLF** [comment]
А почему в календаре потребовалась такая функция _gotoToday? Там же по идее можно проще написать.

**Comment by Nelliza** [comment]
> А почему в календаре потребовалась такая функция _gotoToday? Там же по идее можно проще написать.

Это переопределенный стандартный метод плагина Jquery UI Datepicker, для того чтобы возвращался и день, и месяц при нажатии на кнопку, т.к. по дефолту метод возвращает только текущий месяц

**Comment by MorganaLF** [comment]
> и ему нужно имя класса для добавления модификатора соответствующему DOM-элементу

да, тут наверное лучше так оставить)

Мне тоже кажется, лучше отдельную папку создать. А в один блок нельзя никак объединить pie cahrt и percentage?

**Comment by MorganaLF** [comment]
> Это переопределенный стандартный метод плагина Jquery UI Datepicker

Лучше так не делать, тем более, что есть решения проще. Можешь у меня посмотреть, я этим же плагином пользовалась.

**Comment by Nelliza** [comment]
> > и ему нужно имя класса для добавления модификатора соответствующему DOM-элементу
> 
> да, тут наверное лучше так оставить)
> 
> Мне тоже кажется, лучше отдельную папку создать. А в один блок нельзя никак объединить pie cahrt и percentage?

Думаю нет, т.к. там стили и особенно разметка разнятся

**Comment by Nelliza** [comment]
> > Это переопределенный стандартный метод плагина Jquery UI Datepicker
> 
> Лучше так не делать, тем более, что есть решения проще. Можешь у меня посмотреть, я этим же плагином пользовалась.

Ок, спасибо, посмотрю )

**Comment by MorganaLF** [comment]
Еще кое-что нужно поправить:

**Form.js**
Проверки, содержащие больше одного условия, лучше выносить в переменные
![Снимок экрана_2019-08-09_20-10-16](https://user-images.githubusercontent.com/38564412/62796388-cfe7e580-bae1-11e9-8013-97fb8ba4838d.png)

Дальше ошибки, нарушающие бэм. 
**Promo.js** и **Reservation.js** лезут в другие блоки, 

![Снимок экрана_2019-08-09_20-13-20](https://user-images.githubusercontent.com/38564412/62796517-281ee780-bae2-11e9-8c51-dbf38591ea09.png)

![Снимок экрана_2019-08-09_20-14-52](https://user-images.githubusercontent.com/38564412/62796630-5c92a380-bae2-11e9-97a4-5ab59cf6ddb8.png)

В **slidersInit** и **stagesInit** у тебя используются селекторы, содержащие родительский блок, блоки ничего не должны знать об обертке родителя, в которой они расположены.

![Снимок экрана_2019-08-09_20-17-56](https://user-images.githubusercontent.com/38564412/62796809-cad76600-bae2-11e9-94b4-7a604d154f38.png)

И когда завершишь все правки, проверь eslint-ом всё, сейчас там есть ошибки.

**Comment by Nelliza** [comment]
> Дальше ошибки, нарушающие бэм.
> **Promo.js** и **Reservation.js** лезут в другие блоки,

Насчет **Reservation.js** не соглашусь - блок ведь может содержать другие блоки по БЭМ (https://ru.bem.info/methodology/key-concepts/#Вложенная-структура), мне кажется, здесь норм - внутри reservation ищем вложенные блоки, как думаешь?

**Comment by MorganaLF** [comment]
Блоки могут содержать другие блоки, но они не могут влиять друг на друга. Глядя на блок, всегда должно быть понятно, как он будет себя вести, независимо от контекста. Это то же самое, как писать селектор `.parent .children` для стилизации - дочерний блок становится зависимым от родительского. Вот здесь описано, как могут взаимодействовать друг с другом блоки: https://ru.bem.info/methodology/js/#%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0%D0%BC%D0%B8

**Comment by MorganaLF** [comment]
То есть ты можешь создавать внутри родительского блока экземпляры классов дочерних, вызывать их методы или слушать события, но вся работа непосредственно с дочерним блоком должна происходить в нем самом.

**Comment by Nelliza** [comment]
Да, теперь понятно, вот эта часть ишью особенно полезной оказалась - в процессе вылезли моменты, которые напрашивались на рефакторинг, много чего пришлось переписать, но как-то логичнее все стало

**Comment by MorganaLF** [comment]
Вот здесь еще, где ты ищешь `stages` и `stages__item`, я думаю, лучше их передавать как параметры в класс, раз они не относятся к блоку

![Снимок экрана_2019-08-11_10-14-14](https://user-images.githubusercontent.com/38564412/62831001-0a0bd100-bc21-11e9-997a-a4d8edbb312c.png)
