### ISSUE TITLE
Захардкоженность

### ISSUE THREAD

**Issue by MorganaLF** [Nelliza/hotel#15]
Вот этот текст наверняка должен быть изменяемым:

![Снимок экрана_2019-08-09_20-46-55](https://user-images.githubusercontent.com/38564412/62798417-e2185280-bae6-11e9-8e73-e8d8c44bd382.png)

То же самое в **messaging.pug**

Посмотри еще по проекту, где такое встречается

**Comment by MorganaLF** [comment]
У слайдеров желательно задавать настройки через data-атрибуты в pug

**Comment by Nelliza** [comment]
> У слайдеров желательно задавать настройки через data-атрибуты в pug

Исправлено ранее в рамках ишью #14
