### ISSUE TITLE
Inputs

### ISSUE THREAD

**Issue by MorganaLF** [Nelliza/hotel#17]
В форме на данный момент не работает валидация. Валидацию можно сделать и без js, при помощи атрибута pattern.

И еще обрати внимание, что у тебя у email-а и поиска указан type="text", хотя для этих полей есть специальные типы.

**Comment by Nelliza** [comment]
> В форме на данный момент не работает валидация. Валидацию можно сделать и без js, при помощи атрибута pattern.

Валидация есть, она реализована на js и срабатывает при нажатии на кнопку отправки. Я так поняла, ты хочешь, чтобы валидация срабатывала динамически при анфокусе инпутов? Если так, то как считаешь, ограничиться редактированием js-кода или все же использовать pattern?

**Comment by MorganaLF** [comment]
Не обратила внимание, что валидация при отправке происходила. Ну ничего, валидация по анфокусу, или даже в процессе ввода тоже часто будет пригождаться, так что полезный навык)
