### ISSUE TITLE
demo page

### ISSUE THREAD

**Issue by Frolikow** [Nelliza/hotel#3]
1) при сборке много ошибок выскакивает. 
![image](https://user-images.githubusercontent.com/25764783/61434836-38b7c400-a961-11e9-9370-8c887a55ab5f.png)
![image](https://user-images.githubusercontent.com/25764783/61434850-42d9c280-a961-11e9-8d59-5d95ed891c28.png)

2) по странице которая на gh-pages
+ кнопки поплыли 
![image](https://user-images.githubusercontent.com/25764783/61434958-8c2a1200-a961-11e9-963e-ef811062c368.png)

+ для блока drop-down. Выпадающий список имеет конкретный стиль. В psd посмотри, там слой скрыт.
![image](https://user-images.githubusercontent.com/25764783/61435026-bed40a80-a961-11e9-8e16-94f344985ea8.png)
![image](https://user-images.githubusercontent.com/25764783/61435263-4caff580-a962-11e9-98c9-af6a8e5b4496.png)

+ На календаре, когда переключаешь месяца, иногда верстка под календарем "прыгает". Как вариант - сделать фиксированную обертку на календарем.

+ нужно всю страницу разместить по середине, у меня в бок уползла: 
![image](https://user-images.githubusercontent.com/25764783/61435473-b6300400-a962-11e9-8988-15b7cb79c818.png)

+ step-slider. Надо подравнять значения, чтоб они ровнее были под ползунком
![image](https://user-images.githubusercontent.com/25764783/61435545-e677a280-a962-11e9-944d-c104588cc8c4.png)

+ textarea. Надо убрать изменяемость размера
![image](https://user-images.githubusercontent.com/25764783/61435642-2b033e00-a963-11e9-98ac-6d371c5f6bb8.png)

+ это же для чата
![image](https://user-images.githubusercontent.com/25764783/61435682-43735880-a963-11e9-899f-4b8bf5da2cdb.png)

 + на всех инпутах надо убрать outline при фокусе
![image](https://user-images.githubusercontent.com/25764783/61435741-6e5dac80-a963-11e9-8d7d-eaa8b5db68c2.png)

И сразу скажу, если не используешь, то самое время начать использовать PerfectPixel)

**Comment by Nelliza** [comment]
> * кнопки поплыли

 Это в мозилле наверное? Вчера специально для нее подправляла стили кнопок, странно, через localhost при сборке все норм отображалось (

> И сразу скажу, если не используешь, то самое время начать использовать PerfectPixel)

Использую для хрома и для мозиллы, но они немного разнятся, у мозиллы более строгий ) А т.к. у меня браузер по умолчанию - хром, я больше на него ориентировалась.
Может тогда сразу отдельный ишью для подгонки под мозилловский PerfectPixel открою?

**Comment by Frolikow** [comment]
Все хорошо. Но еще несколько замечаний осталось
1) Давай в чате  с кнопок, которые рядом с аватаром, тоже уберем аутлайны
2) По макету некоторые кнопки не совпадают
 + в форме
 + в блоке евент
 + в чате, кнопка отправки
___
поправь и закрываем ишью

**Comment by Frolikow** [comment]
1) готово
2) увы не готово
  + там по макету посмотри, у кнопок другое состояние. В форме и чате цвет другой. В эвентах кнопка по дефолту имеет тень.
по-поводу цветов кнопок, предлагаю добавить модификатор, например _inverse. Который будет дефолтные цвета менять. 
И кстати чуть не забыл от куда это требование. В первом блоке с кнопками, по макету кнопки все разные, 1 строка это нажатые с рипл эфектом, 2 строка это кнопки в обычном состоянии(с выключенным рипл эфектом), а 3 строка это какраз таки кнопки с обратными цветами(цвет рипла тоже). 
Так что будет смысл вынести рипл в аттрибут миксина и юзать модификатор.
