### ISSUE TITLE
Стили

### ISSUE THREAD

**Issue by Frolikow** [Nelliza/hotel#4]
+ Не понятно почему такая запись 
![image](https://user-images.githubusercontent.com/25764783/61436240-94d01780-a964-11e9-8512-4e6645110107.png)
такая запись не работает?(не могу проверить т.к.не собирается проект)
![image](https://user-images.githubusercontent.com/25764783/61436422-f1333700-a964-11e9-874d-1cdf520bb2f0.png)
+ селекторы по тегу нельзя использовать
![image](https://user-images.githubusercontent.com/25764783/61436563-42432b00-a965-11e9-923b-af61903517fc.png)
+ такую запись 
![image](https://user-images.githubusercontent.com/25764783/61436667-7e768b80-a965-11e9-91fc-0160a2892cc0.png)
можно переписать так 
![image](https://user-images.githubusercontent.com/25764783/61436781-b5e53800-a965-11e9-97c4-a744b4f06709.png)

**Comment by Nelliza** [comment]
>   такая запись не работает?(не могу проверить т.к.не собирается проект)
>   ![image](https://user-images.githubusercontent.com/25764783/61436422-f1333700-a964-11e9-874d-1cdf520bb2f0.png)

Неа, не работает, он ругается на двойной амперсанд (

**Comment by Frolikow** [comment]
в стилях локации тоже надо переписать чтоб дублирования не было. Модификатор на отдельную строчку вынести, а значения модификатора оставить.
Вот здесь тоже можно вынести модификатор отдельно 
![image](https://user-images.githubusercontent.com/25764783/61576259-f083d780-ab01-11e9-8b75-a0f7b3e17f1a.png)
И здесь
![image](https://user-images.githubusercontent.com/25764783/61576354-6b99bd80-ab03-11e9-8726-4bbcd0966e43.png)
