### ISSUE TITLE
PerfectPixel

### ISSUE THREAD

**Issue by MorganaLF** [Nelliza/hotel#8]
Использовался ли в работе PerfectPixel и с какими настройками? Сейчас есть расхождения:

![Снимок экрана в 2019-08-05 10-09-31](https://user-images.githubusercontent.com/38564412/62445587-4050d880-b769-11e9-87bd-a6f1ddd1cb1e.png)

**Comment by MorganaLF** [comment]
В блоке form, думаю, лучше сделать, чтобы в непроверенном состоянии инпуты занимали доступную ширину формы, иначе пустое место выглядит странно)

![Снимок экрана в 2019-08-05 10-15-19](https://user-images.githubusercontent.com/38564412/62446069-7a6eaa00-b76a-11e9-9eac-a37af717cad8.png)

**Comment by Nelliza** [comment]
> Использовался ли в работе PerfectPixel и с какими настройками? Сейчас есть расхождения:

Это в хроме так? У меня намного симпатичнее в хроме выглядит:
![1](https://user-images.githubusercontent.com/19621113/62571284-43df7f00-b891-11e9-9ef7-b43682187184.png)
Может, дело в масштабе? Попробую что-нибудь придумать

**Comment by MorganaLF** [comment]
Да, в хроме, масштаб вроде тот же. Изображение ведь используешь то, что у тебя в assets лежит?

**Comment by Nelliza** [comment]
Да, оно, у меня диагональ монитора небольшая, может поэтому. Я попробовала поиграться с масштабом, при 75% съезжает, но чуть лучше, чем у тебя на скрине 
![2](https://user-images.githubusercontent.com/19621113/62571846-ad13c200-b892-11e9-9aa2-51b735a557ac.png)
Сейчас попробую подогнать )

**Comment by MorganaLF** [comment]
Что-то снова немного едет)

![Снимок экрана_2019-08-08_21-50-26](https://user-images.githubusercontent.com/38564412/62729472-aae26c80-ba26-11e9-883a-7d2f4d0a77bc.png)
![Снимок экрана_2019-08-08_21-50-58](https://user-images.githubusercontent.com/38564412/62729473-aae26c80-ba26-11e9-83db-2b4379b8168a.png)

**Comment by Nelliza** [comment]
> Что-то снова немного едет)

А это потому что мне ориентироваться не на что, кроме твоих скринов, у меня в хроме по-другому выглядит )

**Comment by MorganaLF** [comment]
Теперь сошлось)
