### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by MorganaLF** [Nelliza/hotel#9]
В блоке `about `присутствует элемент блока `page`

![Снимок экрана в 2019-08-05 10-26-35](https://user-images.githubusercontent.com/38564412/62446501-87d86400-b76b-11e9-8920-a11fe3c18e83.png)

То же самое в `footer`

![Снимок экрана в 2019-08-05 10-35-00](https://user-images.githubusercontent.com/38564412/62446935-bc98eb00-b76c-11e9-86d7-db0994e9a4dc.png)

menu:

![Снимок экрана в 2019-08-05 10-37-46](https://user-images.githubusercontent.com/38564412/62447046-17324700-b76d-11e9-937b-6dec1b8cb6b8.png)

promo (здесь ведь можно создать элемент блока promo и передать его при инициализации плагина owl carousel). То же самое в reservation.

![Снимок экрана в 2019-08-05 10-44-08](https://user-images.githubusercontent.com/38564412/62447520-3f6e7580-b76e-11e9-936e-484a40725014.png)

![Снимок экрана в 2019-08-05 10-48-54](https://user-images.githubusercontent.com/38564412/62447707-a2f8a300-b76e-11e9-856a-fe11c7fab6d5.png)

**Comment by MorganaLF** [comment]
Блокам нельзя задавать внешнее позиционирование. Сейчас margin-ы присутствуют у блоков `rooms-item` и `social-icon`

**Comment by MorganaLF** [comment]
Также посмотри по проекту, в некоторых местах встречается использование id, что противоречит БЭМ.

**Comment by MorganaLF** [comment]
В css не должно быть правил для других блоков, в каждом файле блока должны храниться только его собственные стили:

![Снимок экрана в 2019-08-05 11-47-00](https://user-images.githubusercontent.com/38564412/62451380-dccda780-b776-11e9-8c18-8eccf4d9c571.png)

То же самое для блоков **callback, menu-item, page, reservation.** Если необходимо кастомизировать блок, то для него делается модификатор, если спозиционировать - обертка.

**Comment by Nelliza** [comment]
> Также посмотри по проекту, в некоторых местах встречается использование id, что противоречит БЭМ.

Убрала id, использовавшийся для прокрутки к календарю. Остались toggle и tick-box, где id используется для стилизации чекбоксов, а также карта, где создание контейнера с id требуется для работы с API Яндекс.Карт.

**Comment by MorganaLF** [comment]
Блок page обнаружился во всех pug-файлах папки pages, без миксина

**Comment by MorganaLF** [comment]
С блоком page все еще что-то не то, его элементы лежат вне его миксина. Если это что-то специфичное для страниц, то лучше сделать блоки и элементы, по названию соответствующие страницам: contact, в нем contacts__contact-us-wrapper и т.п. Если что-то универсальное для всех страниц, оно уже просится в отдельный миксин. Не знаю, понятно ли объяснила, если что, спрашивай

**Comment by Nelliza** [comment]
> С блоком page все еще что-то не то, его элементы лежат вне его миксина. Если это что-то специфичное для страниц, то лучше сделать блоки и элементы, по названию соответствующие страницам: contact, в нем contacts__contact-us-wrapper и т.п. Если что-то универсальное для всех страниц, оно уже просится в отдельный миксин. Не знаю, понятно ли объяснила, если что, спрашивай

Все понятно объяснила ) Меня тоже смущал момент с этим миксином, просто я думала, что элементы блока page будут тогда присутствовать в других блоках (например, page__content, page__wrapper и т.д.). Сейчас я посмотрела, там особо, кроме page__subtitle, общих элементов не будет, т.е. элементы &__content, &__wrapper, &__callback, &__footer вполне могут быть элементами общего блока hotel, например, вместо page, т.к. присутствуют только на страницах сайта отеля, а в макете их нет. В общем, дальнейший курс действий примерно поняла )

**Comment by MorganaLF** [comment]
Наверное, все-таки плохо объяснила) Смотри, если у тебя есть страница index.pug, то в ней может описываться только .index, index__element. Соответственно, для этих целей будет свой файл стилей и своя папка. Все остальное только инклюдится через миксины, если есть такая необходимость.

**Comment by MorganaLF** [comment]
То есть .page-item уже выглядит как другой блок.

**Comment by Nelliza** [comment]
> То есть .page-item уже выглядит как другой блок.

То есть вместо .page-item я их называю .index__item, .contacts__item, .reservation__item и т.д., так? И в файлах стилей к каждому блоку просто прописываю одно и то же значение. Или я все-таки не так поняла? Вот эти обертки .page-item, .page-centering просто общие для всех этих блоков, с одинаковыми стилями, поэтому я их и вынесла в отдельный блок. Но их ведь нельзя отдельным блоком хотя бы потому, что внешние отступы запрещено присваивать блокам.

**Comment by MorganaLF** [comment]
Если тебе нужен именно блок `.page-item`, то у него должна быть своя папка, свой миксин и свой файл стилей. И использовать его можно только в рамках миксина, в других файлах не должно встречаться `.page-item`. А там уже в зависимости от ситуации, если слишком много общих стилей - то да, целесообразно выделить в отдельный блок, если же там какое-то одно css-правило, то проще сделать это с помощью элементов других блоков, я думаю.
